-- Plant catalog seed (generated from the original seed.ts; edit here from now on).
INSERT OR IGNORE INTO `plant` (`name`, `family`, `emoji`, `spacing`, `sun`) VALUES
('Tomato', 'Solanaceae', '🍅', 1.5, 'full'),
('Pepper', 'Solanaceae', '🌶️', 1, 'full'),
('Eggplant', 'Solanaceae', '🍆', 1.5, 'full'),
('Potato', 'Solanaceae', '🥔', 1, 'full'),
('Kale', 'Brassicaceae', '🥬', 1, 'full'),
('Broccoli', 'Brassicaceae', '🥦', 1.5, 'full'),
('Cabbage', 'Brassicaceae', '🥬', 1.5, 'full'),
('Cauliflower', 'Brassicaceae', '🥦', 1.5, 'full'),
('Radish', 'Brassicaceae', '🌱', 0.25, 'full'),
('Arugula', 'Brassicaceae', '🌿', 0.25, 'partial'),
('Turnip', 'Brassicaceae', '🌱', 0.25, 'full'),
('Brussels Sprouts', 'Brassicaceae', '🥦', 2, 'full'),
('Kohlrabi', 'Brassicaceae', '🥬', 0.5, 'full'),
('Cucumber', 'Cucurbitaceae', '🥒', 1, 'full'),
('Zucchini', 'Cucurbitaceae', '🥒', 2, 'full'),
('Pumpkin', 'Cucurbitaceae', '🎃', 3, 'full'),
('Winter Squash', 'Cucurbitaceae', '🎃', 2, 'full'),
('Melon', 'Cucurbitaceae', '🍈', 1.5, 'full'),
('Watermelon', 'Cucurbitaceae', '🍉', 2, 'full'),
('Bush Bean', 'Fabaceae', '🫘', 0.25, 'full'),
('Pole Bean', 'Fabaceae', '🫘', 0.5, 'full'),
('Pea', 'Fabaceae', '🫛', 0.25, 'full'),
('Onion', 'Amaryllidaceae', '🧅', 0.25, 'full'),
('Garlic', 'Amaryllidaceae', '🧄', 0.5, 'full'),
('Leek', 'Amaryllidaceae', '🧅', 0.25, 'full'),
('Shallot', 'Amaryllidaceae', '🧅', 0.25, 'full'),
('Chives', 'Amaryllidaceae', '🌿', 0.25, 'full'),
('Carrot', 'Apiaceae', '🥕', 0.25, 'full'),
('Cilantro', 'Apiaceae', '🌿', 0.25, 'partial'),
('Dill', 'Apiaceae', '🌿', 0.5, 'full'),
('Parsley', 'Apiaceae', '🌿', 0.25, 'partial'),
('Lettuce', 'Asteraceae', '🥬', 0.25, 'partial'),
('Endive', 'Asteraceae', '🥬', 0.5, 'partial'),
('Sunflower', 'Asteraceae', '🌻', 1, 'full'),
('Spinach', 'Amaranthaceae', '🥬', 0.25, 'partial'),
('Swiss Chard', 'Amaranthaceae', '🥬', 0.5, 'partial'),
('Beet', 'Amaranthaceae', '🟤', 0.25, 'full'),
('Basil', 'Lamiaceae', '🌿', 0.25, 'full'),
('Mint', 'Lamiaceae', '🌿', 0.5, 'partial'),
('Thyme', 'Lamiaceae', '🌿', 0.25, 'full'),
('Oregano', 'Lamiaceae', '🌿', 0.25, 'full'),
('Rosemary', 'Lamiaceae', '🌿', 1.5, 'full'),
('Sage', 'Lamiaceae', '🌿', 1, 'full'),
('Strawberry', 'Rosaceae', '🍓', 0.5, 'full'),
('Sweet Corn', 'Poaceae', '🌽', 0.5, 'full');
